### ISSUE TITLE
Failed install due to dependencies restrictions

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/plotly-resampler-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In setting up a new system, I'm getting this error when attempting to install this:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

The recipe file looks very restrictive in what it requires; is there any way to add some flexibility to it?

### Installed packages

```shell
# Name                    Version                   Build  Channel
brotli-python             1.0.9           py310h1105856_7    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
click                     8.1.3           py310hbe9552e_0    conda-forge
dash                      2.6.0              pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 1.2.0              pyhd8ed1ab_0    conda-forge
flask                     2.1.3              pyhd8ed1ab_0    conda-forge
flask-compress            1.12               pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4          py310hbe9552e_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
libblas                   3.9.0           15_osxarm64_openblas    conda-forge
libcblas                  3.9.0           15_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
liblapack                 3.9.0           15_osxarm64_openblas    conda-forge
libopenblas               0.3.20          openmp_h130de29_1    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
markupsafe                2.1.1           py310hf8d0d8f_1    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.23.1          py310h0a343b5_0    conda-forge
openssl                   3.0.5                ha287fd2_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310ha6a5cd6_0    conda-forge
pip                       22.2.1             pyhd8ed1ab_0    conda-forge
plotly                    5.9.0              pyhd8ed1ab_0    conda-forge
pymysql                   1.0.2              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
python                    3.10.5          h4eee789_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
scipy                     1.9.0           py310hdb41229_0    conda-forge
setuptools                63.2.0          py310hbe9552e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.2               h40dfcc0_0    conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
werkzeug                  2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               ha287fd2_2    conda-forge
```

### Environment info

```shell
active environment : tmba
    active env location : /Users/white/conda/envs/tmba
            shell level : 1
       user config file : /Users/white/.condarc
 populated config files : /Users/white/conda/.condarc
                          /Users/white/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __osx=12.5=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/white/conda  (writable)
      conda av data dir : /Users/white/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /Users/white/conda/pkgs
                          /Users/white/.conda/pkgs
       envs directories : /Users/white/conda/envs
                          /Users/white/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Darwin/21.6.0 OSX/12.5
                UID:GID : 687:15
             netrc file : None
           offline mode : False
```

**Comment by thewchan** [comment]
I've pushed a newer build that might resolve this, please wait a couple hours before trying again. Thanks

**Comment by darynwhite** [comment]
Unfortunately, this didn't resolve it. I'm attempting to install it as the only requested and it fails as well:

```
❯ conda create -n resampler plotly-resampler

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              

UnsatisfiableError: 
```

**Comment by thewchan** [comment]
I'm unable to replicate this on my system; it installs without problem. What version of Python are you using in your virtual environment? Have you tried using `mamba` instead (use as a drop in replacement for `conda`)? What OS are you using? I am able to install on both Windows and Linux. What does the `UnsatisfiableError: ` say? Did it list which packages were in conflict?

**Comment by darynwhite** [comment]
I'm working on setting up a M1 MacBook Pro after being on an Intel iMac. The iMac has no problems.

If I try to build the environment, I get this output:
```
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python_abi conflicts for:
scipy -> python_abi[version='3.10.*|3.9.*|3.8.*',build='*_cp38|*_cp310|*_cp39']
plotly-resampler -> numpy[version='>=1.21.0'] -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']
xarray -> numpy[version='>=1.19'] -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']
pandas -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']
dash-bootstrap-components -> setuptools -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']
jinja2 -> markupsafe[version='>=2.0'] -> python_abi[version='3.10.*|3.9.*|3.8.*',build='*_cp38|*_cp310|*_cp39']
pymysql -> cryptography -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']
plotly -> setuptools -> python_abi[version='3.10.*|3.8.*|3.9.*',build='*_cp38|*_cp39|*_cp310']

Package plotly conflicts for:
dash-bootstrap-components -> dash[version='>=2.0.0'] -> plotly[version='>=5.0.0']
plotly
plotly-resampler -> dash[version='>=2.2.0'] -> plotly[version='>=5.0.0']
plotly-resampler -> plotly[version='>=5.3.1|>=5.6.0|>=5.6.0,<6.0.0']

Package numpy-base conflicts for:
scipy -> numpy[version='>=1.19.5,<2.0a0'] -> numpy-base[version='1.19.2|1.19.2|1.21.2|1.21.2|1.21.2|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.22.3',build='py39hdc56644_1|py310h6269429_0|py38h6269429_0|py38h974a1f5_1|py310h5e3e9f0_1|py310h5e3e9f0_2|py310h742c864_3|py310h5e3e9f0_0|py38h974a1f5_0|py39h974a1f5_0|py39hadd41eb_3|py38hadd41eb_3|py39h974a1f5_2|py38h974a1f5_2|py39h974a1f5_1|py39h6269429_0|py38hdc56644_1']
xarray -> numpy[version='>=1.19'] -> numpy-base[version='1.19.2|1.19.2|1.21.2|1.21.2|1.21.2|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.22.3',build='py39hdc56644_1|py310h6269429_0|py38h6269429_0|py38h974a1f5_1|py310h5e3e9f0_1|py310h5e3e9f0_2|py310h742c864_3|py310h5e3e9f0_0|py38h974a1f5_0|py39h974a1f5_0|py39hadd41eb_3|py38hadd41eb_3|py39h974a1f5_2|py38h974a1f5_2|py39h974a1f5_1|py39h6269429_0|py38hdc56644_1']
pandas -> numpy[version='>=1.19.5,<2.0a0'] -> numpy-base[version='1.19.2|1.19.2|1.21.2|1.21.2|1.21.2|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.22.3',build='py39hdc56644_1|py310h6269429_0|py38h6269429_0|py38h974a1f5_1|py310h5e3e9f0_1|py310h5e3e9f0_2|py310h742c864_3|py310h5e3e9f0_0|py38h974a1f5_0|py39h974a1f5_0|py39hadd41eb_3|py38hadd41eb_3|py39h974a1f5_2|py38h974a1f5_2|py39h974a1f5_1|py39h6269429_0|py38hdc56644_1']
plotly-resampler -> numpy[version='>=1.21.0'] -> numpy-base[version='1.21.2|1.21.2|1.21.2|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.21.5|1.22.3',build='py310h6269429_0|py38h6269429_0|py38h974a1f5_1|py310h5e3e9f0_1|py310h5e3e9f0_2|py310h742c864_3|py310h5e3e9f0_0|py38h974a1f5_0|py39h974a1f5_0|py39hadd41eb_3|py38hadd41eb_3|py39h974a1f5_2|py38h974a1f5_2|py39h974a1f5_1|py39h6269429_0']

Package packaging conflicts for:
pandas -> numexpr[version='>=2.7.1'] -> packaging
xarray -> packaging[version='>=20.0']

Package pytz conflicts for:
plotly-resampler -> pandas[version='>=1.3.5'] -> pytz[version='>=2017.2|>=2020.1|>=2017.3']
pandas -> pytz[version='>=2017.2|>=2020.1|>=2017.3']
xarray -> pandas[version='>=1.2'] -> pytz[version='>=2017.2|>=2020.1|>=2017.3']
plotly -> pytz

Package pandas conflicts for:
xarray -> pandas[version='>=0.19.2|>=0.24|>=0.25|>=1.0|>=1.1|>=1.2']
plotly-resampler -> pandas[version='>=1.3.5|>=1.3.5,<2.0.0']
pandas

Package six conflicts for:
pymysql -> cryptography -> six[version='>=1.4.1']
plotly-resampler -> flask-cors[version='>=3.0.10'] -> six[version='>=1.15.0']
plotly -> tenacity[version='>=6.2.0'] -> six[version='>=1.7.0|>=1.9.0']
xarray -> packaging[version='>=20.0'] -> six
pandas -> python-dateutil[version='>=2.8.1'] -> six[version='>=1.5']
plotly -> six[version='1.15.0|>=1.15.0']

Package libgfortran5 conflicts for:
scipy -> libgfortran=5 -> libgfortran5
scipy -> libgfortran5[version='>=11.0.0.dev0|>=11.0.1.dev0|>=11.1.0']

Package libcblas conflicts for:
scipy -> libcblas[version='>=3.9.0,<4.0a0']
scipy -> blas=[build=openblas] -> libcblas==3.9.0[build='2_openblas|5_openblas|7_openblas|8_openblas|11_osxarm64_openblas|12_osxarm64_openblas|14_osxarm64_openblas|15_osxarm64_openblas|13_osxarm64_openblas|10_openblas|9_openblas|6_openblas|4_openblas|3_openblas|1_openblas']

Package idna conflicts for:
pymysql -> cryptography -> idna
plotly -> requests -> idna[version='>=2.5,<3|>=2.5,<4']

Package dash-bootstrap-components conflicts for:
plotly-resampler -> dash-bootstrap-components[version='>=0.13.1']
dash-bootstrap-components

Package zlib conflicts for:
plotly-resampler -> python[version='>=3.7.1,<3.11'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
plotly -> python[version='>=3.6'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
pandas -> python[version='>=3.8,<3.9.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
xarray -> python[version='>=3.8'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
scipy -> python[version='>=3.9,<3.10.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
tabulate -> python[version='2.7.*|>=3.5'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
pymysql -> python[version='>=3.6'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
jinja2 -> python[version='>=3.7'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']
dash-bootstrap-components -> python[version='>=3.6'] -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0']

Package libblas conflicts for:
scipy -> libblas[version='>=3.9.0,<4.0a0']
scipy -> libcblas[version='>=3.9.0,<4.0a0'] -> libblas[version='3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='2_openblas|5_openblas|8_openblas|13_osxarm64_accelerate|14_osxarm64_openblas|15_osxarm64_accelerate|15_osxarm64_openblas|14_osxarm64_accelerate|13_osxarm64_openblas|12_osxarm64_accelerate|12_osxarm64_openblas|11_osxarm64_openblas|10_openblas|9_openblas|7_openblas|6_openblas|4_openblas|3_openblas|1_openblas']

Package libopenblas conflicts for:
scipy -> libblas[version='>=3.9.0,<4.0a0'] -> libopenblas[version='>=0.3.12,<0.3.13.0a0|>=0.3.15,<0.3.16.0a0|>=0.3.17,<0.3.18.0a0|>=0.3.18,<0.3.19.0a0|>=0.3.20,<0.3.21.0a0|>=0.3.20,<1.0a0|>=0.3.18,<1.0a0|>=0.3.15,<1.0a0|>=0.3.12,<1.0a0']
scipy -> libopenblas[version='>=0.3.17,<1.0a0']

Package setuptools conflicts for:
plotly-resampler -> dash[version='>=2.2.0'] -> setuptools[version='<60.0.0']
plotly -> setuptools
pandas -> setuptools[version='<60.0.0']
pandas -> numexpr[version='>=2.7.1'] -> setuptools
xarray -> setuptools[version='>=40.4|>=41.2']
jinja2 -> setuptools
dash-bootstrap-components -> setuptools
xarray -> pandas[version='>=1.2'] -> setuptools[version='<60.0.0']

Package python conflicts for:
xarray -> python[version='>=3.5|>=3.5.3|>=3.6|>=3.7|>=3.8']
xarray -> numpy[version='>=1.19'] -> python[version='>=2.7|>=3.10,<3.11.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0|>=3',build=*_cpython]

Package certifi conflicts for:
pandas -> setuptools[version='<60.0.0'] -> certifi[version='>=2016.9.26']
xarray -> setuptools[version='>=40.4'] -> certifi[version='>=2016.9.26']
jinja2 -> setuptools -> certifi[version='>=2016.9.26']
dash-bootstrap-components -> setuptools -> certifi[version='>=2016.9.26']
plotly -> setuptools -> certifi[version='>=2016.9.26|>=2017.4.17']

Package liblapack conflicts for:
scipy -> liblapack[version='>=3.9.0,<4.0a0']
scipy -> blas=[build=openblas] -> liblapack==3.9.0[build='2_openblas|5_openblas|7_openblas|8_openblas|11_osxarm64_openblas|12_osxarm64_openblas|14_osxarm64_openblas|15_osxarm64_openblas|13_osxarm64_openblas|10_openblas|9_openblas|6_openblas|4_openblas|3_openblas|1_openblas']

Package retrying conflicts for:
plotly-resampler -> jupyter-dash[version='>=0.4.2'] -> retrying
plotly -> retrying[version='>=1.3.3']
```

But I am able to add `plotly-resampler` via `pip` without any problems. It's definitely confusing!

**Comment by thewchan** [comment]
It is likely that certain dependency has a M1 build that isn't available on Conda Forge yet. One thing I would suggest trying is to downgrade to earlier versions of Python, and see if the conflicts resolves.

**Comment by darynwhite** [comment]
If you mean at the base of my conda install, I may do that yet. Otherwise, when I try to start an environment based solely on `plotly-resampler` this is what I see:

```
> conda create -n resampler plotly-resampler                                                                                                                                    

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              

UnsatisfiableError:
```

I may just need to wait for a little until some additional updates come through.

**Comment by thewchan** [comment]
yes, try this: `conda create -n resampler python==3.9.* plotly-resampler` or some version even lower

**Comment by darynwhite** [comment]
Well, that results in nothing as well. Even attempting a YAML file construction:
```yaml
name: resampler
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.*
  - plotly-resampler
```

results in:

```
❯ conda env create -f resampler.yml                                                                                                                                             ~
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
plotly-resampler -> python[version='>=3.6,<3.11|>=3.7.1,<3.11|>=3.7']
python=3
plotly-resampler -> dash[version='>=2.2.0'] -> python[version='2.7.*|>=3.5|>=3.10,<3.11.0a0|>=3.10,<3.11.0a0|>=3.3|>=3.6|>=3.5|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0',build=*_cpython]
```

**Comment by thewchan** [comment]
This probably speaks to what I said before, that some dependency is not available for M1 yet on Conda Forge, unfortunately. If you can still install via pip that's a work around, just be sure to install anything with pip _last_ in a conda environement.

**Comment by darynwhite** [comment]
Thanks! I'll close this and revisit it in a month or two. If things look different, then I'll comment here to reopen.
